### ISSUE TITLE
The autograd might not work as expected

### ISSUE THREAD

**Issue by rouniuyizu** [RobinBruegger/RevTorch#11]
It took me quite a few days and I think I might spot a bug. 
The whole ReversibleSequence won't backprop under certain situations, and IMHO following line of code is the root cause.
https://github.com/RobinBruegger/RevTorch/blob/bff49ecf092c73729ab240935d902ac211ebf376/revtorch/revtorch.py#L199
Without any parameter in this network module, it won't change the *grad status* from input. In other words, if x.required_grad = False, the output won't require grad either. All the grad requests from subnet(in f/g block) won't surface because of following line:
https://github.com/RobinBruegger/RevTorch/blob/bff49ecf092c73729ab240935d902ac211ebf376/revtorch/revtorch.py#L47
The example won't have this problem because it has "self.conv1 = nn.Conv2d(3, 32, 3)" which will turn x to be grad required so that the whole DAG get linked together.

**Comment by RobinBruegger** [comment]
Thanks for reporting this. Will have a look at it in the coming days, as
soon as I find some time. In the meantime, could you provide a pull request
that fixes it?

rouniuyizu <notifications@github.com> schrieb am Fr., 9. Okt. 2020, 07:03:

**Comment by rouniuyizu** [comment]
I haven't figured out an elegent way to fix this yet... We'll see.
