### ISSUE TITLE
Trying to backward through the graph a second time ... Specify retain_graph=True

### ISSUE THREAD

**Issue by lucidrains** [RobinBruegger/RevTorch#7]
Hi Robin,

I'm back again with another issue. When I attempt to use RevTorch on a more sophisticated architecture, I run into this problem, tracing back to `fx2.backward(dx1)`. The backpropagation must be attempting to backwards through the reversible sequence twice, and therefore throws the error above since it is handled manually. I am also seeing a secondary error when I attempt to fix this by adding `retain_graphs = True` to the above, where because the `ctx.y` and `ctx.reversible_blocks` are freed earlier, they cannot be accessed. I'm not quite sure how to handle this except with a flag in ReversibleSequence class that percolates down and fixes all these issues. Let me know if you have any suggestion!

**Comment by RobinBruegger** [comment]
I currently lack the time to dig deep into this. Would it be possible for you to provide a pull request?

**Comment by lucidrains** [comment]
I'm not an expert with custom backprop, but I created a PR anyways for your review https://github.com/RobinBruegger/RevTorch/pull/8 Memory increases were negligible compared to the amount I saved even with this flag turned off

**Comment by lucidrains** [comment]
Thank you!

**Comment by RobinBruegger** [comment]
Thanks for the PR @lucidrains ! I have released version 0.2.4
